version: '3'
services:
  redis-server:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  app:
    build: ./backend
    ports:
      - "8081:8081"
    links:
      - redis-server
    depends_on:
      - redis-server
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - './:/app'
      - '/app/node_modules'
    command: npm start
    depends_on:
      - app
